# Generated by Django 2.1.2 on 2018-10-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goku',
            fields=[
                ('id_rescatado', models.AutoField(primary_key=True, serialize=False)),
                ('img_rescatado', models.ImageField(blank=True, null=True, upload_to='goku/%Y/%m/$d/')),
                ('nombre_rescatado', models.CharField(max_length=15)),
                ('raza_rescatado', models.CharField(max_length=30)),
                ('descrip_rescatado', models.TextField()),
                ('estado_rescatado', models.CharField(choices=[('Rescatado', 'rescatado'), ('Disponible', 'disponible'), ('Adoptado', 'adoptado')], max_length=15)),
            ],
        ),
    ]
