# Generated by Django 2.1.2 on 2018-10-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0002_auto_20181024_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goku',
            old_name='descripcion_rescatado',
            new_name='descripcion_lomito',
        ),
        migrations.RenameField(
            model_name='goku',
            old_name='estado_rescatado',
            new_name='estado_lomito',
        ),
        migrations.RenameField(
            model_name='goku',
            old_name='id_rescatado',
            new_name='id_lomito',
        ),
        migrations.RenameField(
            model_name='goku',
            old_name='imagen_rescatado',
            new_name='imagen_lomito',
        ),
        migrations.RenameField(
            model_name='goku',
            old_name='nombre_rescatado',
            new_name='nombre_lomito',
        ),
        migrations.RenameField(
            model_name='goku',
            old_name='raza_rescatado',
            new_name='raza_lomito',
        ),
    ]
