# Generated by Django 2.1.2 on 2018-10-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0004_formjb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formjb',
            name='ingresar_fecha',
            field=models.CharField(max_length=30),
        ),
    ]
